### ISSUE TITLE
Is my vechain ever accessable like what does it do just sitting there i can see it in my trust wallet but unsure why it went to werever it is this is the adress

### ISSUE THREAD

**Issue by smit1234567** [vechain/b32#19]
0x871Af1984566E8B2638f90Cb45fA8a1178D0D02f
 This is my etherium address that exodus shows for receiving.and the trust wallet shows the same address with the vechain balance but its not accessable i brought vechain on my exodus account and it dissapeared now i can only veiw the balance in my trust wallet? No clue whats going on here and what the point of hidding it is? 

0x8734440ff8cbb83c10124b6494f56a6f63c74fe7e472f776f17c7b5df8fee2e1
This is also the tranaction code can someone email me with a answer please. Email address is smit123@hotmail.co.nz

Cheers josh

**Comment by libotony** [comment]
Please contact support@vechain.com for further assistance
